// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANdP1idlaEAC0Ndu6aZTx9C0unoVihRg8',
    appId: '1:664136709310:web:6f0eeeca1bd0b087281aef',
    messagingSenderId: '664136709310',
    projectId: 'recursion-app',
    authDomain: 'recursion-app.firebaseapp.com',
    storageBucket: 'recursion-app.appspot.com',
    measurementId: 'G-13S14GK033',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2N0eXDc4KCtqNFF7rapnndCK5oT4yxQc',
    appId: '1:664136709310:android:be1577ed6c09ce2e281aef',
    messagingSenderId: '664136709310',
    projectId: 'recursion-app',
    storageBucket: 'recursion-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_MpJOOcDfpUAwzdjWgwj-h4LKt3EFSyw',
    appId: '1:664136709310:ios:a3837d7a8088357e281aef',
    messagingSenderId: '664136709310',
    projectId: 'recursion-app',
    storageBucket: 'recursion-app.appspot.com',
    iosBundleId: 'com.example.recursionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_MpJOOcDfpUAwzdjWgwj-h4LKt3EFSyw',
    appId: '1:664136709310:ios:152dcfa4c20f7ccf281aef',
    messagingSenderId: '664136709310',
    projectId: 'recursion-app',
    storageBucket: 'recursion-app.appspot.com',
    iosBundleId: 'com.example.recursionApp.RunnerTests',
  );
}
